#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
KickGuard Temporal-Graph V7.1
=============================

Design goals after V7 EventFix diagnostics:
- reuse validated event-aware reduced caches; never re-parse raw data unless missing
- learn event proximity as a continuous risk target instead of only 0/1
- augment the feature space with direction-invariant anomaly features
- use Temporal Graph only as a weak correction
- optionally blend with the previously proven TimeAware/old blend debug CSV
- never use OOF positive rate to decide final positive count
- emit fixed Top-K candidates: 112/116/120/124/128/132

Run from this directory, using the same work_v7 generated by EventFix:

python kickguard_v7_1.py \
  --train-dir ../train \
  --test-dir ../test \
  --work-dir ./work_v7 \
  --output-dir ./v7_1_submit

Optional old TimeAware blend:
  --timeaware-debug ./timeaware_blend_debug.csv

The external blend is optional. If the CSV is absent, V7.1 runs standalone.
"""
from __future__ import annotations

import argparse
import json
import math
import re
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesRegressor, HistGradientBoostingRegressor, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler

import kickguard_v7 as base

CACHE_TAG = "v7_1_risk_1"
OLD_REDUCED_TAG = "v7_eventfix_1"
TOPKS = [112, 116, 120, 124, 128, 132]


def finite(x, default=0.0):
    try:
        return float(x) if np.isfinite(x) else default
    except Exception:
        return default


def safe_rank01(x):
    x = np.asarray(x, dtype=float)
    bad = ~np.isfinite(x)
    if bad.any():
        med = np.nanmedian(x)
        if not np.isfinite(med):
            med = 0.0
        x = x.copy(); x[bad] = med
    if len(x) <= 1:
        return np.zeros_like(x, dtype=float)
    order = np.argsort(np.argsort(x, kind="mergesort"), kind="mergesort")
    return order.astype(float) / float(len(x) - 1)


def risk_from_delta(delta_sec: int) -> float:
    """Continuous event-proximity target. No post-event samples are used."""
    d = float(delta_sec)
    if d <= 300:   # 0-5 min
        return 1.00
    if d <= 600:   # 5-10 min
        return 0.90
    if d <= 1200:  # 10-20 min
        return 0.75
    if d <= 1800:  # 20-30 min
        return 0.60
    if d <= 2700:  # 30-45 min
        return 0.35
    if d <= 3600:  # 45-60 min
        return 0.15
    return 0.0


def binary_from_delta(delta_sec: int) -> int:
    return int(delta_sec <= base.POSITIVE_HORIZON)


def make_feature(df, event, delta):
    end_time = event - pd.Timedelta(seconds=int(delta))
    tmin, tmax = df["__time"].min(), df["__time"].max()
    if end_time <= tmin or end_time > tmax:
        return None
    seg = base.slice_by_end_time(df, end_time, history=1800)
    if seg is None:
        return None
    try:
        f, _, _, _, regime, _ = base.extract_features(seg)
    except Exception:
        return None
    return f, int(regime)


def spread_take(items, n):
    if n <= 0 or not items:
        return []
    if len(items) <= n:
        return list(items)
    ii = np.unique(np.rint(np.linspace(0, len(items) - 1, n)).astype(int))
    return [items[i] for i in ii][:n]


def build_well_risk_samples(df, well, target_far=75):
    event = pd.Timestamp(base.EVENT_TIMES[well])

    # Positive/event-proximity region: every minute from 30 s to 30 min.
    pos_deltas = np.arange(30, 1800 + 1, 60, dtype=int)
    # Boundary region 31-60 min: high-value hard negatives / low-risk transition.
    boundary_deltas = np.arange(1860, 3600 + 1, 60, dtype=int)
    # Far negatives: 63 min to 6 h, sampled sparsely and spread over time.
    far_deltas = np.arange(3780, 21600 + 1, 180, dtype=int)

    pos, boundary, far = [], [], []

    def collect(delta, bucket):
        got = make_feature(df, event, int(delta))
        if got is None:
            return
        f, regime = got
        bucket.append((f, regime, int(delta)))

    for d in pos_deltas:
        collect(d, pos)
    for d in boundary_deltas:
        collect(d, boundary)
    for d in far_deltas:
        collect(d, far)

    if len(pos) < 5:
        raise RuntimeError(f"{well}: only {len(pos)} positive/event samples")

    # Keep all boundary samples. Far negatives are capped to prevent dense wells
    # from dominating sparse wells such as WELL_000005.
    far_sel = spread_take(far, target_far)
    samples = pos + boundary + far_sel

    X = np.vstack([s[0] for s in samples]).astype(np.float32)
    regimes = np.asarray([s[1] for s in samples], dtype=np.int8)
    deltas = np.asarray([s[2] for s in samples], dtype=np.int32)
    y = np.asarray([binary_from_delta(d) for d in deltas], dtype=np.int8)
    risk = np.asarray([risk_from_delta(d) for d in deltas], dtype=np.float32)

    print(
        f"[V7.1 samples] {well}: n={len(y)}, pos={int(y.sum())}, neg={int((y==0).sum())}, "
        f"boundary={len(boundary)}, far={len(far_sel)}/{len(far)}"
    )
    return X, y, risk, regimes, deltas


def build_train_risk_cache(train_dir: Path, work_dir: Path, force=False):
    cache = work_dir / f"train_{CACHE_TAG}.npz"
    if cache.exists() and not force:
        print(f"[cache] {cache}")
        z = np.load(cache, allow_pickle=True)
        return z["X"], z["y"], z["risk"], z["groups"], z["regimes"], z["deltas"]

    Xs=[]; ys=[]; rs=[]; gs=[]; ops=[]; ds=[]
    for gi in range(1, 11):
        well = f"WELL_{gi:06d}"
        reduced = work_dir / f"{well}_reduced_{OLD_REDUCED_TAG}.pkl"
        if reduced.exists() and not force:
            print(f"[cache] {reduced}")
            df = pd.read_pickle(reduced)
            base.validate_event_range(df, well)
        else:
            df = base.load_well_from_train(train_dir, well)
            df.to_pickle(reduced)
        X, y, risk, regimes, deltas = build_well_risk_samples(df, well)
        Xs.append(X); ys.append(y); rs.append(risk); ops.append(regimes); ds.append(deltas)
        gs.append(np.full(len(y), gi-1, dtype=np.int8))

    X=np.vstack(Xs).astype(np.float32)
    y=np.concatenate(ys); risk=np.concatenate(rs); groups=np.concatenate(gs)
    regimes=np.concatenate(ops); deltas=np.concatenate(ds)
    np.savez_compressed(cache, X=X, y=y, risk=risk, groups=groups, regimes=regimes, deltas=deltas)
    print(f"[V7.1 train] X={X.shape}, pos={int(y.sum())}, neg={int((y==0).sum())}")
    return X,y,risk,groups,regimes,deltas


def fill_matrix(X, med=None):
    X=np.asarray(X,dtype=np.float32)
    if med is None:
        med=np.nanmedian(X,axis=0).astype(np.float32)
        med[~np.isfinite(med)]=0.0
    Z=X.copy()
    rr,cc=np.where(~np.isfinite(Z))
    if len(rr): Z[rr,cc]=med[cc]
    Z=np.clip(Z,-1e6,1e6)
    return Z,med


def direction_invariant_expand(X, med=None, scaler=None, fit=False):
    """Keep signed features, plus invariant magnitude/deviation features."""
    Xf, med = fill_matrix(X, med)
    if fit:
        center=np.median(Xf,axis=0).astype(np.float32)
        q25=np.percentile(Xf,25,axis=0).astype(np.float32)
        q75=np.percentile(Xf,75,axis=0).astype(np.float32)
        scale=(q75-q25).astype(np.float32)
        scale[(~np.isfinite(scale)) | (scale<1e-5)]=1.0
        scaler=(center,scale)
    center,scale=scaler
    dev=np.clip((Xf-center)/scale,-30,30)
    mag=np.abs(dev)
    # log magnitude compresses large well-to-well offsets.
    logmag=np.log1p(mag)
    # Row summaries add anomaly intensity without direction.
    row=np.column_stack([
        np.mean(mag,axis=1),
        np.std(mag,axis=1),
        np.percentile(mag,75,axis=1),
        np.percentile(mag,90,axis=1),
        np.percentile(mag,95,axis=1),
        np.max(np.clip(mag,0,50),axis=1),
    ]).astype(np.float32)
    # Retain signed normalized features + direction-invariant log magnitude.
    out=np.concatenate([dev.astype(np.float32),logmag.astype(np.float32),row],axis=1)
    return out,med,scaler


def fit_risk_ensemble(X, y, risk, seed=3407):
    Xa,med,inv_scaler=direction_invariant_expand(X,fit=True)

    etr=ExtraTreesRegressor(
        n_estimators=650,min_samples_leaf=2,max_features="sqrt",n_jobs=-1,random_state=seed
    )
    etr.fit(Xa,risk)

    hgr=HistGradientBoostingRegressor(
        learning_rate=0.035,max_iter=320,max_leaf_nodes=31,min_samples_leaf=12,
        l2_regularization=2.0,random_state=seed
    )
    hgr.fit(Xa,risk)

    # Auxiliary classifier keeps explicit competition-boundary information.
    etc=ExtraTreesClassifier(
        n_estimators=500,min_samples_leaf=2,max_features="sqrt",class_weight={0:1.0,1:1.8},
        n_jobs=-1,random_state=seed+17
    )
    etc.fit(Xa,y)

    # A simple linear branch on anomaly magnitudes improves extrapolation.
    ss=StandardScaler()
    Xs=ss.fit_transform(Xa)
    lr=LogisticRegression(C=0.15,max_iter=2000,class_weight={0:1.0,1:1.8},random_state=seed+31)
    lr.fit(Xs,y)

    return {"med":med,"inv_scaler":inv_scaler,"etr":etr,"hgr":hgr,"etc":etc,"ss":ss,"lr":lr}


def predict_risk_ensemble(model,X):
    Xa,_,_=direction_invariant_expand(X,med=model["med"],scaler=model["inv_scaler"],fit=False)
    p1=np.clip(model["etr"].predict(Xa),0,1)
    p2=np.clip(model["hgr"].predict(Xa),0,1)
    p3=model["etc"].predict_proba(Xa)[:,1]
    p4=model["lr"].predict_proba(model["ss"].transform(Xa))[:,1]
    # Rank-space blending prevents one poorly calibrated branch dominating.
    r=(0.38*safe_rank01(p1)+0.27*safe_rank01(p2)+0.25*safe_rank01(p3)+0.10*safe_rank01(p4))
    return np.clip(r,0,1), {"etr":p1,"hgr":p2,"etc":p3,"lr":p4}


def competition_metric(y,pred):
    y=np.asarray(y,dtype=int); pred=np.asarray(pred,dtype=int)
    tp=int(np.sum((y==1)&(pred==1))); fn=int(np.sum((y==1)&(pred==0)))
    tn=int(np.sum((y==0)&(pred==0))); fp=int(np.sum((y==0)&(pred==1)))
    rec=tp/max(tp+fn,1); spec=tn/max(tn+fp,1)
    return 100.0*rec*rec*spec,rec,spec,tp,fn,fp,tn


def topk_pred(score,k):
    k=int(np.clip(k,1,len(score)-1)); pred=np.zeros(len(score),dtype=np.int8)
    pred[np.argsort(-score)[:k]]=1
    return pred


def loso_risk(X,y,risk,groups):
    oof=np.zeros(len(y),dtype=float); rows=[]
    for g in np.unique(groups):
        tr=groups!=g; va=groups==g
        model=fit_risk_ensemble(X[tr],y[tr],risk[tr],seed=7400+int(g))
        p,_=predict_risk_ensemble(model,X[va]); oof[va]=p
        yv=y[va]
        auc=float(roc_auc_score(yv,p)) if np.unique(yv).size==2 else float("nan")
        # Ranking diagnostic only: predict 38% positive, close to historically useful test region.
        k=max(int(yv.sum()),round(len(yv)*0.38))
        pred=topk_pred(p,k)
        m=competition_metric(yv,pred)
        rows.append({"well":int(g)+1,"auc":auc,"rank_score":m[0],"recall":m[1],"specificity":m[2],"k":int(k)})
        print(f"[V7.1 LOSO] WELL_{int(g)+1:06d} AUC={auc:.5f} RankScore@{k}={m[0]:.5f} Recall={m[1]:.5f} Spec={m[2]:.5f}")
    try: overall_auc=float(roc_auc_score(y,oof))
    except Exception: overall_auc=float("nan")
    print(f"[V7.1 OOF] AUC={overall_auc:.6f}")
    return oof,rows,overall_auc


def discover_timeaware(path_arg, work_dir):
    candidates=[]
    if path_arg: candidates.append(Path(path_arg))
    candidates += [
        Path("./timeaware_blend_debug.csv"),
        work_dir/"timeaware_blend_debug.csv",
        Path("../timeaware_blend_debug.csv"),
    ]
    for p in candidates:
        if p.exists() and p.is_file():
            print(f"[blend] using TimeAware debug: {p.resolve()}")
            return p
    print("[blend] TimeAware debug not found; running V7.1 standalone")
    return None


def load_external_baseline(path, ids):
    if path is None: return None,None
    df=pd.read_csv(path)
    id_col="切片ID" if "切片ID" in df.columns else ("id" if "id" in df.columns else None)
    if id_col is None: raise RuntimeError(f"No test id column in {path}")
    prob_col=None
    for c in ["blend_prob","time_prob","prob","old_prob"]:
        if c in df.columns:
            prob_col=c; break
    if prob_col is None: raise RuntimeError(f"No probability column in {path}; columns={list(df.columns)}")
    mp={str(r[id_col]):float(r[prob_col]) for _,r in df.iterrows()}
    vals=[]; missing=[]
    for sid in ids:
        if sid not in mp: missing.append(sid); vals.append(np.nan)
        else: vals.append(mp[sid])
    if missing:
        raise RuntimeError(f"External baseline missing {len(missing)} ids, e.g. {missing[:5]}")
    return np.asarray(vals,dtype=float),prob_col


def infer_domains_robust(starts,ends,missing,regimes,n_domains=7):
    # Start with base KMeans but use more groups than V7's collapsed 5-way split.
    try:
        return base.infer_hidden_domains(starts,ends,missing,n_domains)
    except Exception:
        # deterministic fallback: missingness signatures + regime
        sig=np.round(np.nan_to_num(missing),2)
        keys=[(int(regimes[i]),tuple(sig[i].tolist())) for i in range(len(regimes))]
        uniq={k:j for j,k in enumerate(dict.fromkeys(keys))}
        return np.asarray([uniq[k] for k in keys],dtype=int)


def graph_adjust(risk_score,starts,ends,missing,regimes,n_domains=7):
    domains=infer_domains_robust(starts,ends,missing,regimes,n_domains=n_domains)
    try:
        edges=base.build_temporal_graph(starts,ends,domains)
        # Use only weak propagation and re-rank. Passing zero anchors avoids old physical-anchor branch dominating.
        graph=base.graph_propagation(risk_score,np.zeros(len(risk_score),dtype=float),edges)
        final=0.92*safe_rank01(risk_score)+0.08*safe_rank01(graph)
    except Exception as e:
        print(f"[graph warning] {e}; graph disabled")
        edges=[]; final=safe_rank01(risk_score)
    return np.asarray(final,dtype=float),domains,edges


def write_zip(ids,pred,path):
    path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
    df=pd.DataFrame({"切片ID":ids,"溢流判断":np.asarray(pred,dtype=int)})
    if len(df)!=324 or df["切片ID"].nunique()!=324:
        raise RuntimeError("Submission must contain exactly 324 unique test ids")
    raw=df.to_csv(index=False,lineterminator="\n").encode("utf-8-sig")
    with zipfile.ZipFile(path,"w",zipfile.ZIP_DEFLATED) as z:
        z.writestr("result.csv",raw)
    print(f"[output] {path} positive={int(df['溢流判断'].sum())}")


def run(args):
    train_dir=Path(args.train_dir).resolve(); test_dir=Path(args.test_dir).resolve()
    work_dir=Path(args.work_dir).resolve(); out_dir=Path(args.output_dir).resolve()
    work_dir.mkdir(parents=True,exist_ok=True); out_dir.mkdir(parents=True,exist_ok=True)
    print(f"[path] train={train_dir}\n[path] test ={test_dir}\n[path] work ={work_dir}\n[path] out  ={out_dir}")

    X,y,risk,groups,train_regimes,deltas=build_train_risk_cache(train_dir,work_dir,args.force_rebuild)
    XT,ids,starts,ends,missing,test_regimes,anchors=base.build_test_features(test_dir,work_dir,force=False)
    if X.shape[1]!=XT.shape[1]:
        raise RuntimeError(f"feature mismatch train={X.shape}, test={XT.shape}")

    oof,per_well,oof_auc=loso_risk(X,y,risk,groups)
    pd.DataFrame({"well":groups+1,"label":y,"risk_target":risk,"delta_sec":deltas,"oof_score":oof}).to_csv(work_dir/"V7_1_oof.csv",index=False)

    print("[V7.1 final] fitting all wells")
    model=fit_risk_ensemble(X,y,risk,seed=8801)
    p_risk,branches=predict_risk_ensemble(model,XT)
    p_graph,domains,edges=graph_adjust(p_risk,starts,ends,missing,test_regimes,args.hidden_domains)

    baseline_path=discover_timeaware(args.timeaware_debug,work_dir)
    p_base,base_col=load_external_baseline(baseline_path,ids)
    if p_base is not None:
        # TimeAware/old model stays dominant because it previously validated much better than V7.
        final_score=(
            args.baseline_weight*safe_rank01(p_base)
            + args.risk_weight*safe_rank01(p_risk)
            + args.graph_weight*safe_rank01(p_graph)
        )
        mode=f"external:{base_col}"
    else:
        # Standalone fallback. Graph remains weak.
        final_score=0.88*safe_rank01(p_risk)+0.12*safe_rank01(p_graph)
        mode="standalone"
    final_score=safe_rank01(final_score)

    debug=pd.DataFrame({
        "切片ID":ids,"risk_score":p_risk,"graph_score":p_graph,"final_score":final_score,
        "domain":domains,"regime":test_regimes,"physical_anchor":anchors,
        "etr":branches["etr"],"hgr":branches["hgr"],"etc":branches["etc"],"lr":branches["lr"],
    })
    if p_base is not None: debug["external_baseline"]=p_base
    debug["rank"]=debug["final_score"].rank(method="first",ascending=False).astype(int)
    debug.sort_values("rank").to_csv(work_dir/"V7_1_test_debug.csv",index=False)

    candidate_counts=sorted(set(TOPKS + ([args.main_k] if args.main_k else [])))
    outputs=[]
    for k in candidate_counts:
        pred=topk_pred(final_score,k)
        path=out_dir/f"result_v7_1_top{k}.zip"
        write_zip(ids,pred,path); outputs.append(str(path))

    main_k=args.main_k or 120
    main_pred=topk_pred(final_score,main_k)
    main_path=out_dir/"result_v7_1.zip"
    write_zip(ids,main_pred,main_path)

    edge_rows=[]
    for e in edges:
        try:
            edge_rows.append({"src_id":ids[e["src"]],"dst_id":ids[e["dst"]],"domain":e.get("domain",-1),"distance":e.get("distance",np.nan),"confidence":e.get("confidence",np.nan)})
        except Exception:
            pass
    pd.DataFrame(edge_rows).to_csv(work_dir/"V7_1_graph_edges.csv",index=False)

    summary={
        "version":"Temporal-Graph V7.1",
        "train_shape":list(X.shape),"test_shape":list(XT.shape),"oof_auc":finite(oof_auc,-1),
        "per_well":per_well,"blend_mode":mode,"external_baseline":str(baseline_path) if baseline_path else None,
        "weights":{"baseline":args.baseline_weight,"risk":args.risk_weight,"graph":args.graph_weight},
        "graph_edges":len(edges),"domain_counts":np.bincount(domains).tolist() if len(domains) else [],
        "main_k":int(main_k),"candidate_k":candidate_counts,"outputs":outputs+[str(main_path)],
    }
    with open(work_dir/"V7_1_summary.json","w",encoding="utf-8") as f:
        json.dump(summary,f,ensure_ascii=False,indent=2)

    print("="*72)
    print("Temporal-Graph V7.1 completed")
    print(f"OOF AUC      : {oof_auc:.6f}")
    print(f"Blend mode   : {mode}")
    print(f"Graph edges  : {len(edges)}")
    print(f"Domain counts: {summary['domain_counts']}")
    print(f"MAIN         : {main_path} (K={main_k})")
    print(f"SUMMARY      : {work_dir/'V7_1_summary.json'}")
    print("Candidates   : " + ", ".join(str(k) for k in candidate_counts))
    print("="*72)


def parser():
    ap=argparse.ArgumentParser(description="KickGuard Temporal-Graph V7.1 robust risk ensemble")
    ap.add_argument("--train-dir",default="../train")
    ap.add_argument("--test-dir",default="../test")
    ap.add_argument("--work-dir",default="./work_v7")
    ap.add_argument("--output-dir",default="./v7_1_submit")
    ap.add_argument("--timeaware-debug",default=None)
    ap.add_argument("--hidden-domains",type=int,default=7)
    ap.add_argument("--baseline-weight",type=float,default=0.75)
    ap.add_argument("--risk-weight",type=float,default=0.20)
    ap.add_argument("--graph-weight",type=float,default=0.05)
    ap.add_argument("--main-k",type=int,default=120)
    ap.add_argument("--force-rebuild",action="store_true")
    return ap


if __name__=="__main__":
    args=parser().parse_args()
    w=args.baseline_weight+args.risk_weight+args.graph_weight
    if args.timeaware_debug and abs(w-1.0)>1e-6:
        raise SystemExit(f"blend weights must sum to 1.0, got {w}")
    run(args)
